cargo-features = ["per-package-target"]

[package]
name = "dusk-eth-contract"
authors.workspace = true
version.workspace = true
edition.workspace = true

forced-target = "wasm32-unknown-unknown"

[dependencies]
piecrust-uplink = { workspace = true }
dusk-eth-contract-types = { workspace = true }
