cargo-features = ["per-package-target"]

[package]
name = "deth-contract"
authors.workspace = true
version.workspace = true
edition.workspace = true

forced-target = "wasm32-unknown-unknown"

[dependencies]
piecrust-uplink = { workspace = true }
deth-contract-types = { workspace = true }
